/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlgorithmsIndexRouteImport } from './routes/Algorithms/index'
import { Route as AlgorithmsSortingRouteImport } from './routes/Algorithms/sorting'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlgorithmsIndexRoute = AlgorithmsIndexRouteImport.update({
  id: '/Algorithms/',
  path: '/Algorithms/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlgorithmsSortingRoute = AlgorithmsSortingRouteImport.update({
  id: '/Algorithms/sorting',
  path: '/Algorithms/sorting',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Algorithms/sorting': typeof AlgorithmsSortingRoute
  '/Algorithms': typeof AlgorithmsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Algorithms/sorting': typeof AlgorithmsSortingRoute
  '/Algorithms': typeof AlgorithmsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Algorithms/sorting': typeof AlgorithmsSortingRoute
  '/Algorithms/': typeof AlgorithmsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/Algorithms/sorting' | '/Algorithms'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Algorithms/sorting' | '/Algorithms'
  id: '__root__' | '/' | '/Algorithms/sorting' | '/Algorithms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlgorithmsSortingRoute: typeof AlgorithmsSortingRoute
  AlgorithmsIndexRoute: typeof AlgorithmsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Algorithms/': {
      id: '/Algorithms/'
      path: '/Algorithms'
      fullPath: '/Algorithms'
      preLoaderRoute: typeof AlgorithmsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Algorithms/sorting': {
      id: '/Algorithms/sorting'
      path: '/Algorithms/sorting'
      fullPath: '/Algorithms/sorting'
      preLoaderRoute: typeof AlgorithmsSortingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlgorithmsSortingRoute: AlgorithmsSortingRoute,
  AlgorithmsIndexRoute: AlgorithmsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
