/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrganigramRouteImport } from './routes/organigram'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlgorithmsIndexRouteImport } from './routes/algorithms/index'
import { Route as AlgorithmsSearchingRouteImport } from './routes/algorithms/searching'
import { Route as AlgorithmsSortingRouteRouteImport } from './routes/algorithms/sorting/route'
import { Route as AlgorithmsSortingIndexRouteImport } from './routes/algorithms/sorting/index'
import { Route as AlgorithmsSortingSelectionSortRouteImport } from './routes/algorithms/sorting/selectionSort'
import { Route as AlgorithmsSortingQuickSortRouteImport } from './routes/algorithms/sorting/quickSort'
import { Route as AlgorithmsSortingMergeSortRouteImport } from './routes/algorithms/sorting/mergeSort'
import { Route as AlgorithmsSortingInsertionSortRouteImport } from './routes/algorithms/sorting/insertionSort'
import { Route as AlgorithmsSortingBubbleSortRouteImport } from './routes/algorithms/sorting/bubbleSort'

const OrganigramRoute = OrganigramRouteImport.update({
  id: '/organigram',
  path: '/organigram',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlgorithmsIndexRoute = AlgorithmsIndexRouteImport.update({
  id: '/algorithms/',
  path: '/algorithms/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlgorithmsSearchingRoute = AlgorithmsSearchingRouteImport.update({
  id: '/algorithms/searching',
  path: '/algorithms/searching',
  getParentRoute: () => rootRouteImport,
} as any)
const AlgorithmsSortingRouteRoute = AlgorithmsSortingRouteRouteImport.update({
  id: '/algorithms/sorting',
  path: '/algorithms/sorting',
  getParentRoute: () => rootRouteImport,
} as any)
const AlgorithmsSortingIndexRoute = AlgorithmsSortingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AlgorithmsSortingRouteRoute,
} as any)
const AlgorithmsSortingSelectionSortRoute =
  AlgorithmsSortingSelectionSortRouteImport.update({
    id: '/selectionSort',
    path: '/selectionSort',
    getParentRoute: () => AlgorithmsSortingRouteRoute,
  } as any)
const AlgorithmsSortingQuickSortRoute =
  AlgorithmsSortingQuickSortRouteImport.update({
    id: '/quickSort',
    path: '/quickSort',
    getParentRoute: () => AlgorithmsSortingRouteRoute,
  } as any)
const AlgorithmsSortingMergeSortRoute =
  AlgorithmsSortingMergeSortRouteImport.update({
    id: '/mergeSort',
    path: '/mergeSort',
    getParentRoute: () => AlgorithmsSortingRouteRoute,
  } as any)
const AlgorithmsSortingInsertionSortRoute =
  AlgorithmsSortingInsertionSortRouteImport.update({
    id: '/insertionSort',
    path: '/insertionSort',
    getParentRoute: () => AlgorithmsSortingRouteRoute,
  } as any)
const AlgorithmsSortingBubbleSortRoute =
  AlgorithmsSortingBubbleSortRouteImport.update({
    id: '/bubbleSort',
    path: '/bubbleSort',
    getParentRoute: () => AlgorithmsSortingRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/organigram': typeof OrganigramRoute
  '/algorithms/sorting': typeof AlgorithmsSortingRouteRouteWithChildren
  '/algorithms/searching': typeof AlgorithmsSearchingRoute
  '/algorithms': typeof AlgorithmsIndexRoute
  '/algorithms/sorting/bubbleSort': typeof AlgorithmsSortingBubbleSortRoute
  '/algorithms/sorting/insertionSort': typeof AlgorithmsSortingInsertionSortRoute
  '/algorithms/sorting/mergeSort': typeof AlgorithmsSortingMergeSortRoute
  '/algorithms/sorting/quickSort': typeof AlgorithmsSortingQuickSortRoute
  '/algorithms/sorting/selectionSort': typeof AlgorithmsSortingSelectionSortRoute
  '/algorithms/sorting/': typeof AlgorithmsSortingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/organigram': typeof OrganigramRoute
  '/algorithms/searching': typeof AlgorithmsSearchingRoute
  '/algorithms': typeof AlgorithmsIndexRoute
  '/algorithms/sorting/bubbleSort': typeof AlgorithmsSortingBubbleSortRoute
  '/algorithms/sorting/insertionSort': typeof AlgorithmsSortingInsertionSortRoute
  '/algorithms/sorting/mergeSort': typeof AlgorithmsSortingMergeSortRoute
  '/algorithms/sorting/quickSort': typeof AlgorithmsSortingQuickSortRoute
  '/algorithms/sorting/selectionSort': typeof AlgorithmsSortingSelectionSortRoute
  '/algorithms/sorting': typeof AlgorithmsSortingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/organigram': typeof OrganigramRoute
  '/algorithms/sorting': typeof AlgorithmsSortingRouteRouteWithChildren
  '/algorithms/searching': typeof AlgorithmsSearchingRoute
  '/algorithms/': typeof AlgorithmsIndexRoute
  '/algorithms/sorting/bubbleSort': typeof AlgorithmsSortingBubbleSortRoute
  '/algorithms/sorting/insertionSort': typeof AlgorithmsSortingInsertionSortRoute
  '/algorithms/sorting/mergeSort': typeof AlgorithmsSortingMergeSortRoute
  '/algorithms/sorting/quickSort': typeof AlgorithmsSortingQuickSortRoute
  '/algorithms/sorting/selectionSort': typeof AlgorithmsSortingSelectionSortRoute
  '/algorithms/sorting/': typeof AlgorithmsSortingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/organigram'
    | '/algorithms/sorting'
    | '/algorithms/searching'
    | '/algorithms'
    | '/algorithms/sorting/bubbleSort'
    | '/algorithms/sorting/insertionSort'
    | '/algorithms/sorting/mergeSort'
    | '/algorithms/sorting/quickSort'
    | '/algorithms/sorting/selectionSort'
    | '/algorithms/sorting/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/organigram'
    | '/algorithms/searching'
    | '/algorithms'
    | '/algorithms/sorting/bubbleSort'
    | '/algorithms/sorting/insertionSort'
    | '/algorithms/sorting/mergeSort'
    | '/algorithms/sorting/quickSort'
    | '/algorithms/sorting/selectionSort'
    | '/algorithms/sorting'
  id:
    | '__root__'
    | '/'
    | '/organigram'
    | '/algorithms/sorting'
    | '/algorithms/searching'
    | '/algorithms/'
    | '/algorithms/sorting/bubbleSort'
    | '/algorithms/sorting/insertionSort'
    | '/algorithms/sorting/mergeSort'
    | '/algorithms/sorting/quickSort'
    | '/algorithms/sorting/selectionSort'
    | '/algorithms/sorting/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrganigramRoute: typeof OrganigramRoute
  AlgorithmsSortingRouteRoute: typeof AlgorithmsSortingRouteRouteWithChildren
  AlgorithmsSearchingRoute: typeof AlgorithmsSearchingRoute
  AlgorithmsIndexRoute: typeof AlgorithmsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/organigram': {
      id: '/organigram'
      path: '/organigram'
      fullPath: '/organigram'
      preLoaderRoute: typeof OrganigramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/algorithms/': {
      id: '/algorithms/'
      path: '/algorithms'
      fullPath: '/algorithms'
      preLoaderRoute: typeof AlgorithmsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/algorithms/searching': {
      id: '/algorithms/searching'
      path: '/algorithms/searching'
      fullPath: '/algorithms/searching'
      preLoaderRoute: typeof AlgorithmsSearchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/algorithms/sorting': {
      id: '/algorithms/sorting'
      path: '/algorithms/sorting'
      fullPath: '/algorithms/sorting'
      preLoaderRoute: typeof AlgorithmsSortingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/algorithms/sorting/': {
      id: '/algorithms/sorting/'
      path: '/'
      fullPath: '/algorithms/sorting/'
      preLoaderRoute: typeof AlgorithmsSortingIndexRouteImport
      parentRoute: typeof AlgorithmsSortingRouteRoute
    }
    '/algorithms/sorting/selectionSort': {
      id: '/algorithms/sorting/selectionSort'
      path: '/selectionSort'
      fullPath: '/algorithms/sorting/selectionSort'
      preLoaderRoute: typeof AlgorithmsSortingSelectionSortRouteImport
      parentRoute: typeof AlgorithmsSortingRouteRoute
    }
    '/algorithms/sorting/quickSort': {
      id: '/algorithms/sorting/quickSort'
      path: '/quickSort'
      fullPath: '/algorithms/sorting/quickSort'
      preLoaderRoute: typeof AlgorithmsSortingQuickSortRouteImport
      parentRoute: typeof AlgorithmsSortingRouteRoute
    }
    '/algorithms/sorting/mergeSort': {
      id: '/algorithms/sorting/mergeSort'
      path: '/mergeSort'
      fullPath: '/algorithms/sorting/mergeSort'
      preLoaderRoute: typeof AlgorithmsSortingMergeSortRouteImport
      parentRoute: typeof AlgorithmsSortingRouteRoute
    }
    '/algorithms/sorting/insertionSort': {
      id: '/algorithms/sorting/insertionSort'
      path: '/insertionSort'
      fullPath: '/algorithms/sorting/insertionSort'
      preLoaderRoute: typeof AlgorithmsSortingInsertionSortRouteImport
      parentRoute: typeof AlgorithmsSortingRouteRoute
    }
    '/algorithms/sorting/bubbleSort': {
      id: '/algorithms/sorting/bubbleSort'
      path: '/bubbleSort'
      fullPath: '/algorithms/sorting/bubbleSort'
      preLoaderRoute: typeof AlgorithmsSortingBubbleSortRouteImport
      parentRoute: typeof AlgorithmsSortingRouteRoute
    }
  }
}

interface AlgorithmsSortingRouteRouteChildren {
  AlgorithmsSortingBubbleSortRoute: typeof AlgorithmsSortingBubbleSortRoute
  AlgorithmsSortingInsertionSortRoute: typeof AlgorithmsSortingInsertionSortRoute
  AlgorithmsSortingMergeSortRoute: typeof AlgorithmsSortingMergeSortRoute
  AlgorithmsSortingQuickSortRoute: typeof AlgorithmsSortingQuickSortRoute
  AlgorithmsSortingSelectionSortRoute: typeof AlgorithmsSortingSelectionSortRoute
  AlgorithmsSortingIndexRoute: typeof AlgorithmsSortingIndexRoute
}

const AlgorithmsSortingRouteRouteChildren: AlgorithmsSortingRouteRouteChildren =
  {
    AlgorithmsSortingBubbleSortRoute: AlgorithmsSortingBubbleSortRoute,
    AlgorithmsSortingInsertionSortRoute: AlgorithmsSortingInsertionSortRoute,
    AlgorithmsSortingMergeSortRoute: AlgorithmsSortingMergeSortRoute,
    AlgorithmsSortingQuickSortRoute: AlgorithmsSortingQuickSortRoute,
    AlgorithmsSortingSelectionSortRoute: AlgorithmsSortingSelectionSortRoute,
    AlgorithmsSortingIndexRoute: AlgorithmsSortingIndexRoute,
  }

const AlgorithmsSortingRouteRouteWithChildren =
  AlgorithmsSortingRouteRoute._addFileChildren(
    AlgorithmsSortingRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrganigramRoute: OrganigramRoute,
  AlgorithmsSortingRouteRoute: AlgorithmsSortingRouteRouteWithChildren,
  AlgorithmsSearchingRoute: AlgorithmsSearchingRoute,
  AlgorithmsIndexRoute: AlgorithmsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
